Repository blooming-inpeak/inpeak-backend, pull requests merged in 2025-02, with the labels that each got.

#2 chore: 개발 환경 초기 세팅(#1)
  inpeak/build.gradle
  inpeak/compose.yaml
  inpeak/src/main/resources/application.properties
  inpeak/src/main/resources/application.yml
Labels: chore

#4 feat: Auditing fields 및 Error build factory 생성(#3)
  inpeak/src/main/java/com/blooming/inpeak/common/base/AuditingFields.java
  inpeak/src/main/java/com/blooming/inpeak/common/error/ErrorBuildFactory.java
  inpeak/src/main/java/com/blooming/inpeak/common/error/ErrorCode.java
  inpeak/src/main/java/com/blooming/inpeak/common/error/ErrorHandlingController.java
  inpeak/src/main/java/com/blooming/inpeak/common/error/ErrorResponse.java
Labels: feat

#9 chore: redis 구성 및 통합테스트 환경 설정 (#8)
  inpeak/build.gradle
  inpeak/src/main/java/com/blooming/inpeak/common/config/redis/RedisConfiguration.java
  inpeak/src/main/resources/application.yml
  inpeak/src/test/java/com/blooming/inpeak/DefaultSpringBootLoadingTest.java
  inpeak/src/test/java/com/blooming/inpeak/InpeakApplicationTests.java
  inpeak/src/test/java/com/blooming/inpeak/IntegrationTestSupport.java
  inpeak/src/test/java/com/blooming/inpeak/TestRedisConfiguration.java
Labels: chore

#10 feat: 멤버 entity 정의 (#5)
  inpeak/src/main/java/com/blooming/inpeak/member/domain/Member.java
Labels: feat

#22 Feat/#13 interview total count
  inpeak/src/main/java/com/blooming/inpeak/interview/domain/Interview.java
  inpeak/src/main/java/com/blooming/inpeak/interview/dto/response/InterviewTotalCountResponse.java
  inpeak/src/main/java/com/blooming/inpeak/interview/repository/InterviewRepository.java
  inpeak/src/main/java/com/blooming/inpeak/interview/service/InterviewService.java
Labels: feat

#26 feat: Question 엔티티 생성 (#25)
  inpeak/src/main/java/com/blooming/inpeak/answer/domain/Answer.java
  inpeak/src/main/java/com/blooming/inpeak/answer/domain/Interview.java
  inpeak/src/main/java/com/blooming/inpeak/answer/domain/Question.java
  inpeak/src/main/java/com/blooming/inpeak/answer/dto/response/AnswerResponse.java
  inpeak/src/main/java/com/blooming/inpeak/answer/repository/AnswerRepositoryCustom.java
  inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerService.java
  inpeak/src/main/java/com/blooming/inpeak/common/base/BaseEntity.java
  inpeak/src/main/java/com/blooming/inpeak/interview/domain/Interview.java
  inpeak/src/main/java/com/blooming/inpeak/member/domain/Member.java
  inpeak/src/main/java/com/blooming/inpeak/question/domain/Question.java
  inpeak/src/main/java/com/blooming/inpeak/question/domain/QuestionType.java
  inpeak/src/test/java/com/blooming/inpeak/answer/domain/AnswerTest.java
Labels: feat

#28 fix: question - main conflict 해결 (#27)
  inpeak/src/main/java/com/blooming/inpeak/answer/domain/Answer.java
  inpeak/src/main/java/com/blooming/inpeak/answer/dto/response/AnswerResponse.java
  inpeak/src/main/java/com/blooming/inpeak/answer/repository/AnswerRepositoryCustom.java
  inpeak/src/test/java/com/blooming/inpeak/answer/domain/AnswerTest.java
Labels: fix

#30 feat: 정답 리스트 조회 테스트 작성 (#29)
  inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerController.java
  inpeak/src/main/java/com/blooming/inpeak/answer/dto/command/AnswerFilterCommand.java
  inpeak/src/main/java/com/blooming/inpeak/answer/dto/request/AnswerFilterRequest.java
  inpeak/src/main/java/com/blooming/inpeak/answer/repository/AnswerRepositoryCustom.java
  inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerService.java
  inpeak/src/test/java/com/blooming/inpeak/answer/repository/AnswerRepositoryCustomTest.java
  inpeak/src/test/java/com/blooming/inpeak/answer/service/AnswerServiceTest.java
Labels: feat

#32 feat: 오답노트 기능 추가(#31)
  inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerController.java
  inpeak/src/main/java/com/blooming/inpeak/answer/domain/AnswerStatus.java
  inpeak/src/main/java/com/blooming/inpeak/answer/dto/command/AnswerFilterCommand.java
  inpeak/src/main/java/com/blooming/inpeak/answer/dto/request/CorrectAnswerFilterRequest.java
  inpeak/src/main/java/com/blooming/inpeak/answer/dto/request/IncorrectAnswerFilterRequest.java
  inpeak/src/main/java/com/blooming/inpeak/answer/repository/AnswerRepositoryCustom.java
  inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerService.java
  inpeak/src/test/java/com/blooming/inpeak/answer/repository/AnswerRepositoryCustomTest.java
  inpeak/src/test/java/com/blooming/inpeak/answer/service/AnswerServiceTest.java
Labels: feat

#33 feat: 모의면접 잔여 횟수 반환 (#23)
  inpeak/src/main/java/com/blooming/inpeak/interview/dto/response/InterviewTotalCountResponse.java
  inpeak/src/main/java/com/blooming/inpeak/interview/dto/response/RemainingInterviewsResponse.java
  inpeak/src/main/java/com/blooming/inpeak/interview/dto/response/TotalInterviewsResponse.java
  inpeak/src/main/java/com/blooming/inpeak/interview/repository/InterviewRepository.java
  inpeak/src/main/java/com/blooming/inpeak/interview/service/InterviewService.java
Labels: feat

#34 feat: Interview 누적 연습 횟수, 잔여 기회 횟수 테스트 작성 (#24)
  inpeak/src/main/java/com/blooming/inpeak/interview/controller/InterviewController.java
  inpeak/src/test/java/com/blooming/inpeak/interview/domain/InterviewTest.java
  inpeak/src/test/java/com/blooming/inpeak/interview/repository/InterviewRepositoryTest.java
  inpeak/src/test/java/com/blooming/inpeak/interview/service/InterviewServiceTest.java
Labels: feat

#41 feat: JWT 토큰 검증을 위한 filter 추가 (#39)
  inpeak/src/main/java/com/blooming/inpeak/auth/filter/TokenAuthenticationFilter.java
  inpeak/src/main/java/com/blooming/inpeak/auth/handler/OAuth2AuthenticationSuccessHandler.java
  inpeak/src/main/java/com/blooming/inpeak/auth/utils/JwtTokenProvider.java
  inpeak/src/main/java/com/blooming/inpeak/common/config/SecurityConfig.java
  inpeak/src/main/java/com/blooming/inpeak/filter/TokenAuthenticationFilter.java
  inpeak/src/test/java/com/blooming/inpeak/auth/filter/TokenAuthenticationFilterTest.java
  inpeak/src/test/java/com/blooming/inpeak/common/config/SecurityConfigTest.java
  inpeak/src/test/java/com/blooming/inpeak/common/utils/JwtTokenProviderTest.java
Labels: feat

#45 chore: ci 환경 구성 (#43)
  .github/workflows/inpeak-ci.yml
Labels: chore

#46 chore: ci 환경 구성 (#43)
  .github/workflows/inpeak-ci.yml
Labels: chore
