Repository blooming-inpeak/inpeak-backend, pull requests merged in 2025-03, with the labels that each got.

#58 feat: Security filter를 통한 회원가입 검증 로직 개선 (#56)
  inpeak/src/main/java/com/blooming/inpeak/auth/filter/TokenAuthenticationFilter.java
  inpeak/src/main/java/com/blooming/inpeak/auth/service/CustomOAuth2UserService.java
  inpeak/src/main/java/com/blooming/inpeak/member/domain/Member.java
  inpeak/src/main/java/com/blooming/inpeak/member/domain/RegistrationStatus.java
  inpeak/src/test/java/com/blooming/inpeak/answer/repository/AnswerRepositoryCustomTest.java
  inpeak/src/test/java/com/blooming/inpeak/common/utils/JwtTokenProviderTest.java
Labels: feat

#60 refactor: 토큰 인증 필터 예외 처리 및 테스트 개선 (#59)
  inpeak/src/main/java/com/blooming/inpeak/auth/filter/TokenAuthenticationFilter.java
  inpeak/src/test/java/com/blooming/inpeak/auth/filter/TokenAuthenticationFilterTest.java
Labels: refector

#62 feat: 회원 등록 상태에 따른 API 접근 제어 개선 (#61)
  inpeak/src/main/java/com/blooming/inpeak/auth/filter/TokenAuthenticationFilter.java
  inpeak/src/test/java/com/blooming/inpeak/auth/filter/TokenAuthenticationFilterTest.java
Labels: feat, fix

#64 refactor: presigned url 메타데이터 수정 (#63)
  inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerController.java
  inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerPresignedUrlService.java
Labels: refector

#68 feat: 이해 여부 변경 기능 추가(#67)
  inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerController.java
  inpeak/src/main/java/com/blooming/inpeak/answer/domain/Answer.java
  inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerService.java
  inpeak/src/test/java/com/blooming/inpeak/answer/domain/AnswerTest.java
  inpeak/src/test/java/com/blooming/inpeak/answer/service/AnswerServiceTest.java
Labels: feat

#70 feat: 코멘트 작성 기능 추가(#69)
  inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerController.java
  inpeak/src/main/java/com/blooming/inpeak/answer/domain/Answer.java
  inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerService.java
  inpeak/src/test/java/com/blooming/inpeak/answer/service/AnswerServiceTest.java
Labels: feat

#73 feat: 최근 질문 히스토리 구현 (#72)
  inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerController.java
  inpeak/src/main/java/com/blooming/inpeak/answer/dto/response/RecentAnswerListResponse.java
  inpeak/src/main/java/com/blooming/inpeak/answer/dto/response/RecentAnswerResponse.java
  inpeak/src/main/java/com/blooming/inpeak/answer/repository/AnswerRepositoryCustom.java
  inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerService.java
  inpeak/src/test/java/com/blooming/inpeak/answer/repository/AnswerRepositoryCustomTest.java
  inpeak/src/test/java/com/blooming/inpeak/answer/service/AnswerServiceTest.java
Labels: feat

#77 refactor: 응답 형식에 맞게 리펙토링(#76)
  inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerController.java
  inpeak/src/main/java/com/blooming/inpeak/answer/domain/Answer.java
  inpeak/src/main/java/com/blooming/inpeak/answer/dto/command/AnswerCreateCommand.java
  inpeak/src/main/java/com/blooming/inpeak/answer/dto/command/AnswerFilterCommand.java
  inpeak/src/main/java/com/blooming/inpeak/answer/dto/request/AnswerCreateRequest.java
  inpeak/src/main/java/com/blooming/inpeak/answer/dto/request/CommentUpdateRequest.java
  inpeak/src/main/java/com/blooming/inpeak/answer/dto/request/CorrectAnswerFilterRequest.java
  inpeak/src/main/java/com/blooming/inpeak/answer/dto/request/UnderstoodUpdateRequest.java
  inpeak/src/main/java/com/blooming/inpeak/answer/dto/response/AnswerIDResponse.java
  inpeak/src/main/java/com/blooming/inpeak/answer/dto/response/AnswerResponse.java
  inpeak/src/main/java/com/blooming/inpeak/answer/repository/AnswerRepositoryCustom.java
  inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerService.java
  inpeak/src/main/java/com/blooming/inpeak/answer/service/GPTService.java
  inpeak/src/test/java/com/blooming/inpeak/answer/domain/AnswerTest.java
  inpeak/src/test/java/com/blooming/inpeak/answer/repository/AnswerRepositoryCustomTest.java
  inpeak/src/test/java/com/blooming/inpeak/answer/service/AnswerServiceTest.java
Labels: refector

#82 feat: 답변 조회 기능 추가(#81)
  inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerController.java
  inpeak/src/main/java/com/blooming/inpeak/answer/dto/response/AnswerDetailResponse.java
  inpeak/src/main/java/com/blooming/inpeak/answer/repository/AnswerRepository.java
  inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerService.java
  inpeak/src/test/java/com/blooming/inpeak/answer/service/AnswerServiceTest.java
Labels: feat

#85 feat: 회원 관심사 등록 및 수정 API (#71)
  inpeak/src/main/java/com/blooming/inpeak/auth/filter/TokenAuthenticationFilter.java
  inpeak/src/main/java/com/blooming/inpeak/member/controller/MemberInterestController.java
  inpeak/src/main/java/com/blooming/inpeak/member/domain/Member.java
  inpeak/src/main/java/com/blooming/inpeak/member/dto/request/MemberInterestRequest.java
  inpeak/src/main/java/com/blooming/inpeak/member/repository/MemberInterestRepository.java
  inpeak/src/main/java/com/blooming/inpeak/member/service/MemberInterestService.java
  inpeak/src/test/java/com/blooming/inpeak/auth/filter/TokenAuthenticationFilterTest.java
Labels: feat

#89 feat: 모의면접 대시보드 기능 구현 (#84)
  inpeak/src/main/java/com/blooming/inpeak/answer/dto/response/AnswerPresignedUrlResponse.java
  inpeak/src/main/java/com/blooming/inpeak/dashborad/controller/InterviewDashboardController.java
  inpeak/src/main/java/com/blooming/inpeak/dashborad/dto/InterviewDashboardResponse.java
  inpeak/src/main/java/com/blooming/inpeak/dashborad/service/InterviewDashboardService.java
  inpeak/src/main/java/com/blooming/inpeak/interview/dto/response/InterviewStartResponse.java
  inpeak/src/main/java/com/blooming/inpeak/interview/dto/response/RemainingInterviewsResponse.java
  inpeak/src/main/java/com/blooming/inpeak/interview/dto/response/TotalInterviewsResponse.java
  inpeak/src/main/java/com/blooming/inpeak/interview/repository/InterviewRepository.java
  inpeak/src/main/java/com/blooming/inpeak/interview/service/InterviewService.java
  inpeak/src/main/java/com/blooming/inpeak/interview/service/InterviewStartService.java
  inpeak/src/main/java/com/blooming/inpeak/question/dto/response/QuestionResponse.java
  inpeak/src/test/java/com/blooming/inpeak/interview/repository/InterviewRepositoryTest.java
  inpeak/src/test/java/com/blooming/inpeak/interview/service/InterviewServiceTest.java
Labels: feat

#91 feat: 카카오 사용자 식별 방식 변경 email -> kakaoId (#90)
  inpeak/src/main/java/com/blooming/inpeak/InpeakApplication.java
  inpeak/src/main/java/com/blooming/inpeak/auth/controller/AuthController.java
  inpeak/src/main/java/com/blooming/inpeak/auth/filter/TokenAuthenticationFilter.java
  inpeak/src/main/java/com/blooming/inpeak/auth/handler/OAuth2AuthenticationSuccessHandler.java
  inpeak/src/main/java/com/blooming/inpeak/auth/service/CustomOAuth2UserService.java
  inpeak/src/main/java/com/blooming/inpeak/member/domain/Member.java
  inpeak/src/main/java/com/blooming/inpeak/member/domain/OAuth2Provider.java
  inpeak/src/main/java/com/blooming/inpeak/member/dto/MemberPrincipal.java
  inpeak/src/main/java/com/blooming/inpeak/member/dto/OAuth2Command.java
  inpeak/src/main/java/com/blooming/inpeak/member/dto/OAuth2UserInfo.java
  inpeak/src/main/java/com/blooming/inpeak/member/repository/MemberRepository.java
  inpeak/src/test/java/com/blooming/inpeak/answer/repository/AnswerRepositoryCustomTest.java
  inpeak/src/test/java/com/blooming/inpeak/auth/service/CustomOAuth2UserServiceTest.java
  inpeak/src/test/java/com/blooming/inpeak/common/utils/JwtTokenProviderTest.java
  inpeak/src/test/java/com/blooming/inpeak/member/repository/MemberRepositoryTest.java
Labels: feat

#92 feat: member 닉네임 변경 기능 (#54)
  inpeak/src/main/java/com/blooming/inpeak/member/controller/MemberController.java
  inpeak/src/main/java/com/blooming/inpeak/member/domain/Member.java
  inpeak/src/main/java/com/blooming/inpeak/member/dto/request/NincknameUpdateRequest.java
  inpeak/src/main/java/com/blooming/inpeak/member/service/MemberService.java
Labels: feat

#94 feat: OAuth 인증 후 JWT 토큰을 쿠키에 저장하도록 변경 (#93)
  inpeak/src/main/java/com/blooming/inpeak/auth/handler/OAuth2AuthenticationSuccessHandler.java
  inpeak/src/main/resources/application.yml
Labels: feat

#96 feat: 토큰 재발급 API (#95)
  inpeak/src/main/java/com/blooming/inpeak/auth/controller/AuthController.java
  inpeak/src/main/java/com/blooming/inpeak/auth/dto/TokenResponse.java
  inpeak/src/main/java/com/blooming/inpeak/auth/service/AuthService.java
  inpeak/src/main/resources/application.yml
Labels: feat

#98 feat: 대시보드에 정답률 비교 추가 (#97)
  inpeak/src/main/java/com/blooming/inpeak/answer/repository/AnswerRepository.java
  inpeak/src/main/java/com/blooming/inpeak/dashborad/dto/InterviewDashboardResponse.java
  inpeak/src/main/java/com/blooming/inpeak/dashborad/dto/SuccessRateResponse.java
  inpeak/src/main/java/com/blooming/inpeak/dashborad/service/InterviewDashboardService.java
  inpeak/src/main/java/com/blooming/inpeak/dashborad/service/SuccessRateService.java
Labels: feat

#100 feat: member 탈퇴 API (#99)
  inpeak/src/main/java/com/blooming/inpeak/answer/repository/AnswerRepository.java
  inpeak/src/main/java/com/blooming/inpeak/interview/repository/InterviewRepository.java
  inpeak/src/main/java/com/blooming/inpeak/member/controller/MemberController.java
  inpeak/src/main/java/com/blooming/inpeak/member/service/MemberService.java
Labels: feat

#104 feat: 회원 탈퇴 시 S3에 저장된 모의면접 영상 삭제 기능 구현 (#103)
  inpeak/src/main/java/com/blooming/inpeak/answer/domain/Answer.java
  inpeak/src/main/java/com/blooming/inpeak/answer/repository/AnswerRepository.java
  inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerPresignedUrlService.java
  inpeak/src/main/java/com/blooming/inpeak/answer/service/AnswerVideoCleanupService.java
  inpeak/src/main/java/com/blooming/inpeak/member/service/MemberService.java
Labels: feat

#108 feat: Member 엔티티에 이메일 정보 저장 기능 추가 (#107)
  inpeak/src/main/java/com/blooming/inpeak/auth/service/CustomOAuth2UserService.java
  inpeak/src/main/java/com/blooming/inpeak/member/domain/Member.java
  inpeak/src/test/java/com/blooming/inpeak/answer/repository/AnswerRepositoryCustomTest.java
  inpeak/src/test/java/com/blooming/inpeak/auth/service/CustomOAuth2UserServiceTest.java
  inpeak/src/test/java/com/blooming/inpeak/member/repository/MemberRepositoryTest.java
Labels: feat

#110 feat: 마이페이지 조회 API (#106)
  inpeak/src/main/java/com/blooming/inpeak/member/controller/MemberController.java
  inpeak/src/main/java/com/blooming/inpeak/member/dto/response/MyPageResponse.java
  inpeak/src/main/java/com/blooming/inpeak/member/service/MemberService.java
Labels: feat

#112 chore: cors 설정 spring으로 변경 (#111)
  inpeak/src/main/java/com/blooming/inpeak/common/config/SecurityConfig.java
  inpeak/src/main/java/com/blooming/inpeak/common/config/WebConfig.java
Labels: chore

#114 feat: 모든 API 엔드포인트에 prefix 추가 (#113)
  inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerController.java
  inpeak/src/main/java/com/blooming/inpeak/auth/controller/AuthController.java
  inpeak/src/main/java/com/blooming/inpeak/dashborad/controller/InterviewDashboardController.java
  inpeak/src/main/java/com/blooming/inpeak/interview/controller/InterviewController.java
  inpeak/src/main/java/com/blooming/inpeak/member/controller/MemberController.java
  inpeak/src/main/java/com/blooming/inpeak/member/controller/MemberInterestController.java
Labels: feat

#122 feat: 인증 방식을 쿠키 기반으로 전환 (#121)
  inpeak/src/main/java/com/blooming/inpeak/auth/controller/AuthController.java
  inpeak/src/main/java/com/blooming/inpeak/auth/filter/TokenAuthenticationFilter.java
  inpeak/src/main/java/com/blooming/inpeak/auth/handler/OAuth2AuthenticationSuccessHandler.java
  inpeak/src/main/java/com/blooming/inpeak/auth/service/AuthService.java
  inpeak/src/test/java/com/blooming/inpeak/auth/filter/TokenAuthenticationFilterTest.java
Labels: feat
